### ISSUE TITLE
Setting maxpool parameter

### ISSUE THREAD

**Issue by lazaa32** [nyurik/tilelive-pgquery#5]
Hi @nyurik,

I am testing PgQuery and I am a bit confused with `maxpool` parameter. From the READme:
```
maxpool (integer) - size of the connection pool (default=10). If given, must be used once or the same number of times as there are hosts.
```
I am running 2 db-server with 8 cores with following pgquery:
```
pgquery://?database=openmaptiles&host=host-1&host=jost-2&port=5432&username=openmaptiles&password=openmaptiles&funcZXY=getmvt&maxpool=8&nogzip=1&key=1
```
But now I am not sure whether `maxpool` should be `8` or `2*8` or maybe another value? Could you please provide me some insight into this, because I am afraid that right now due to my misunderstanding it is not implemented correctly in omt-tools.
https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-tiles#L45
Thank you.

**Comment by nyurik** [comment]
@lazaa32 `maxpool` is per server because pgquery creates as many pools as there are servers -- that's why if you have servers of different size, e.g. one is 16 core and another is 8 core, you can set it to `maxpool=16&maxpool=8` -- this way first server will have up to 16 connections at the same time.

**Comment by lazaa32** [comment]
@nyurik ok, thanks. And how do you calculate appropriate value for `maxpool`? In OMT-tools there is specific parameter `MAX_HOST_CONNECTION` but if not set, `COPY_CONCURRENCY` is used instead which should be number of CPU per server.  I assumed that `COPY_CONCURRENCY` should be equal to number of CPUs.
https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-tiles#L44
The reason I'm asking is that I accidentally ran 2 servers with 8 CPUs each with `COPY_CONCURRENCY=32` in configuration (I forgot to modify to `COPY_CONCURRENCY=8`). However the tiles generation was faster so I am wondering how to decide the `maxpool` value correctly.

**Comment by nyurik** [comment]
Heh, that's a tricky one - I would think the max pool should be a bit higher than the number of cores in the database server, but it really depends on many different factors like the type of harddrives (ssd vs spin), RAM, etc.  Optimizing PostgreSQL is more of an art than science :)

**Comment by lazaa32** [comment]
Ok, thanks :) I will try to learn some of that art :D
